from enum import Enum

STRING_MISMATCH_FIELD = "#PCDATA"
OPTIONAL_FIELD = ")?"
ITERATOR_FIELD = ")+"
IGNORED_TAGS = ['script', 'style']
HTML_TAG_START = "<"
TOKEN_TYPE = Enum('TOKEN_TYPE', ['DATABASE_FIELD', 'OPENING_TAG', 'CLOSING_TAG', 'ITERATOR', 'OPTIONAL'])
